apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipe4
  template:
    metadata:
      labels:
        app: pipe4
    spec:
      containers:
      - name: pipe4
        image: royjith/cube:version-3.14
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pipe4
