apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe3
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipe3
  template:
    metadata:
      labels:
        app: pipe3
    spec:
      containers:
      - name: pipe3
        image: royjith/cube:version-3.23
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pipe3
